using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Threading.Tasks;
using HFCA;
using SQLite;

namespace HFCA
{
    public class CardDatabase
    {
        readonly SQLiteAsyncConnection _database;

        public CardDatabase(string dbPath)
        {
            _database = new SQLiteAsyncConnection(dbPath);
#if DEBUG
            _database.DropTableAsync<Card>().Wait();
#endif
            var result = _database.CreateTableAsync<Card>().Result;
            if (result == CreateTableResult.Created)
                _database.InsertAllAsync(Data);
        }

        public ObservableCollection<Card> GetCards()
        {
            return new ObservableCollection<Card>(_database.Table<Card>().ToListAsync().Result);
        }

        public Task<Card> GetCard(int id)
        {
            return _database.GetAsync<Card>(id);
        }

        private List<Card> Data => new List<Card>()
        {
            #region Thrusters
            new Card()
            {
                ID = 1,
                OtherSideId = 2,
                SpectralType = SpectralType.V,
                Name = "Ablative Plate\r\n",
                Type = CardType.Thruster,
                Mass = 1,
                RadHard = 7,
                Thrust = 2,
                FuelUse = 2,
                FreeTurns = 0,
                AfterBurn = 1,
                IsPushable = true,
                IsSolarPowered = false,
                Requirements = "XB",
            },
            new Card()
            {
                ID = 2,
                OtherSideId = 1,
                Name = "Ablative Nozzle",
                SpectralType= SpectralType.V,
                Mass = 0,
                RadHard = 8,
                Type = CardType.Thruster,
                Thrust= 3,
                FuelUse = 2,
                FreeTurns = 0,
                AfterBurn = 1,
                IsPushable = true,
                IsSolarPowered = false,
                Requirements = "X~B",
            },
            new Card()
            {
                ID = 3,
                OtherSideId = 4,
                Name = "De Laval Nozzle",
                SpectralType= SpectralType.M,
                Mass = 0,
                RadHard = 6,
                Type = CardType.Thruster,
                Thrust= 5,
                FuelUse = 4,
                FreeTurns = 0,
                AfterBurn = 2,
                IsPushable = false,
                IsSolarPowered = false,
                Requirements = "~B",
            },
            new Card()
            {
                ID = 4,
                OtherSideId = 3,
                Name = "Magnetic Nozzle",
                SpectralType= SpectralType.M,
                Mass = 0,
                RadHard = 5,
                Type = CardType.Thruster,
                Thrust= 3,
                FuelUse = 1,
                FreeTurns = 0,
                AfterBurn = 3,
                IsPushable = false,
                IsSolarPowered = false,
                Requirements = "~",
            },
            new Card()
            {
                ID = 5,
                OtherSideId = 6,
                Name = "Dumbo",
                SpectralType= SpectralType.S,
                Mass = 0,
                RadHard = 7,
                Type = CardType.Thruster,
                Thrust= 6,
                FuelUse = 5,
                FreeTurns = 0,
                AfterBurn = 1,
                IsPushable = false,
                IsSolarPowered = false,
                Requirements = "~B",
            },
            new Card()
            {
                ID = 6,
                OtherSideId = 5,
                Name = "Timberwind",
                SpectralType= SpectralType.S,
                Mass = 0,
                RadHard = 7,
                Type = CardType.Thruster,
                Thrust= 5,
                FuelUse = 3,
                FreeTurns = 0,
                AfterBurn = 1,
                IsPushable = false,
                IsSolarPowered = false,
                Requirements = "X~B",
            },
            new Card()
            {
                ID = 7,
                OtherSideId = 8,
                Name = "Hall Effect",
                SpectralType= SpectralType.C,
                Mass = 2,
                RadHard = 5,
                Type = CardType.Thruster,
                Thrust= 3,
                FuelUse = 2,
                FreeTurns = 0,
                AfterBurn = 0,
                IsPushable = true,
                IsSolarPowered = false,
                Requirements = "e",
            },
            new Card()
            {
                ID = 8,
                OtherSideId = 7,
                Name = "Ion Drive",
                SpectralType= SpectralType.C,
                Mass = 1,
                RadHard = 5,
                Type = CardType.Thruster,
                Thrust= 2,
                FuelUse = 0.5d,
                FreeTurns = 1,
                AfterBurn = 1,
                IsPushable = true,
                IsSolarPowered = false,
                Requirements = "e",
            },
            new Card()
            {
                ID = 9,
                OtherSideId = 10,
                Name = "Mass Driver",
                SpectralType= SpectralType.M,
                Mass = 3,
                RadHard = 8,
                Type = CardType.Thruster,
                Thrust= 4,
                FuelUse = 3,
                FreeTurns = 0,
                AfterBurn = 0,
                IsPushable = true,
                IsSolarPowered = false,
                Requirements = "c",
            },
            new Card()
            {
                ID = 10,
                OtherSideId = 9,
                Name = "MPD T-wave",
                SpectralType= SpectralType.M,
                Mass = 1,
                RadHard = 9,
                Type = CardType.Thruster,
                Thrust= 2,
                FuelUse = 0.5d,
                FreeTurns = 0,
                AfterBurn = 0,
                IsPushable = true,
                IsSolarPowered = false,
                Requirements = "c",
            },
            new Card()
            {
                ID = 11,
                OtherSideId = 12,
                Name = "Metastable Helium",
                SpectralType= SpectralType.V,
                Mass = 1,
                RadHard = 0,
                Type = CardType.Thruster,
                Thrust= 5,
                FuelUse = 1,
                FreeTurns = 0,
                AfterBurn = 1,
                IsPushable = false,
                IsSolarPowered = false,
                Requirements = "X",
                Therms = -1,
            },
            new Card()
            {
                ID = 12,
                OtherSideId = 11,
                Name = "n-6Li Microfission",
                SpectralType= SpectralType.V,
                Mass = 1,
                RadHard = 8,
                Type = CardType.Thruster,
                Thrust= 5,
                FuelUse = 0.5d,
                FreeTurns = 0,
                AfterBurn = 1,
                IsPushable = false,
                IsSolarPowered = false,
                Requirements = "X",
                Therms = -1,
            },
            new Card()
            {
                ID = 13,
                OtherSideId = 14,
                Name = "Monoatomic Plug Nozzle",
                SpectralType= SpectralType.M,
                Mass = 0,
                RadHard = 6,
                Type = CardType.Thruster,
                Thrust= 4,
                FuelUse = 3,
                FreeTurns = 0,
                AfterBurn = 1,
                IsPushable = false,
                IsSolarPowered = false,
                Requirements = "~",
            },
            new Card()
            {
                ID = 14,
                OtherSideId = 13,
                Name = "Vortex Confined Nozzle",
                SpectralType= SpectralType.M,
                Mass = 0,
                RadHard = 7,
                Type = CardType.Thruster,
                Thrust= 4,
                FuelUse = 2,
                FreeTurns = 0,
                AfterBurn = 1,
                IsPushable = false,
                IsSolarPowered = false,
                Requirements = "~",
                Therms = -1,
            },
            new Card()
            {
                ID = 15,
                OtherSideId = 16,
                Name = "Photon Heliogyro",
                SpectralType= SpectralType.C,
                Mass = 0,
                RadHard = 1,
                Type = CardType.Thruster,
                Thrust= 0,
                FuelUse = 0,
                FreeTurns = 1,
                AfterBurn = 0,
                IsPushable = true,
                IsSolarPowered = true,
                Requirements = "",
                Ability = "Aerobrake decommission. Immune to Flare & Belt Rolls.",
            },
            new Card()
            {
                ID = 16,
                OtherSideId = 15,
                Name = "Electric Sail",
                SpectralType= SpectralType.C,
                Mass = 0,
                RadHard = 2,
                Type = CardType.Thruster,
                Thrust= 2,
                FuelUse = 0,
                FreeTurns = 1,
                AfterBurn = 0,
                IsPushable = true,
                IsSolarPowered = true,
                Requirements = "",
                Ability = "Aerobrake decommission. Immune to Flare & Belt Rolls.",
            },
            new Card()
            {
                ID = 17,
                OtherSideId = 18,
                Name = "Photon Kite Sail",
                SpectralType= SpectralType.C,
                Mass = 0,
                RadHard = 0,
                Type = CardType.Thruster,
                Thrust= 0,
                FuelUse = 0,
                FreeTurns = 1,
                AfterBurn = 0,
                IsPushable = true,
                IsSolarPowered = true,
                Requirements = "",
                Ability = "Aerobrake decommission. Immune to Flare & Belt Rolls.",
            },
            new Card()
            {
                ID = 18,
                OtherSideId = 17,
                Name = "Mag Sail",
                SpectralType= SpectralType.C,
                Mass = 0,
                RadHard = 4,
                Type = CardType.Thruster,
                Thrust= 1,
                FuelUse = 0,
                FreeTurns = 1,
                AfterBurn = 0,
                IsPushable = true,
                IsSolarPowered = true,
                Requirements = "",
                Ability = "Aerobrake decommission. Each Radiation Belt entered = Bonus Burn",
            },
            new Card()
            {
                ID = 19,
                OtherSideId = 20,
                Name = "Ponderomotive VASIMR",
                SpectralType= SpectralType.V,
                Mass = 1,
                RadHard = 4,
                Type = CardType.Thruster,
                Thrust= 3,
                FuelUse = 1,
                FreeTurns = 0,
                AfterBurn = 1,
                IsPushable = true,
                IsSolarPowered = false,
                Requirements = "c",
            },
            new Card()
            {
                ID = 20,
                OtherSideId = 19,
                Name = "Pulsed Plasmoid",
                SpectralType= SpectralType.V,
                Mass = 1,
                RadHard = 5,
                Type = CardType.Thruster,
                Thrust = 3,
                FuelUse = 1,
                FreeTurns = 0,
                AfterBurn = 0,
                IsPushable = true,
                IsSolarPowered = true,
                Requirements = "",
            },
            new Card()
            {
                ID = 21,
                OtherSideId = 22,
                Name = "Pulsed Inductive",
                SpectralType= SpectralType.C,
                Mass = 1,
                RadHard = 5,
                Type = CardType.Thruster,
                Thrust = 4,
                FuelUse = 2,
                FreeTurns = 0,
                AfterBurn = 0,
                IsPushable = true,
                IsSolarPowered = false,
                Requirements = "c",
            },
            new Card()
            {
                ID = 22,
                OtherSideId = 21,
                Name = "Dual-Stage 4-Grid",
                SpectralType= SpectralType.C,
                Mass = 0,
                RadHard = 5,
                Type = CardType.Thruster,
                Thrust = 2,
                FuelUse = 1/3d,
                FreeTurns = 1,
                AfterBurn = 0,
                IsPushable = true,
                IsSolarPowered = false,
                Requirements = "e",
            },
            new Card()
            {
                ID = 23,
                OtherSideId = 24,
                Name = "Re Solar Moth",
                SpectralType= SpectralType.D,
                Mass = 0,
                RadHard = 5,
                Type = CardType.Thruster,
                Thrust = 3,
                FuelUse = 4,
                FreeTurns = 0,
                AfterBurn = 2,
                IsPushable = true,
                IsSolarPowered = true,
                Requirements = "",
            },
            new Card()
            {
                ID = 24,
                OtherSideId = 23,
                Name = "Colliding Beam H-B Fusion",
                SpectralType= SpectralType.D,
                Mass = 2,
                RadHard = 5,
                Type = CardType.Thruster,
                Thrust = 3,
                FuelUse = 0.1d,
                FreeTurns = 1,
                AfterBurn = 2,
                IsPushable = false,
                IsSolarPowered = false,
                Requirements = "e",
                Therms = -1,
            },
            #endregion
            #region Reactors
            new Card()
            {
                ID = 25,
                OtherSideId = 26,
                Name = "Cermet NERVA Fission",
                SpectralType= SpectralType.S,
                Mass = 1,
                RadHard = 7,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 3,
                FuelUse = 1,
                Supports = "~",
                Requirements = "",
            },
            new Card()
            {
                ID = 26,
                OtherSideId = 25,
                Name = "Pulsed NTR Fission",
                SpectralType= SpectralType.S,
                Mass = 0,
                RadHard = 7,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 0,
                FuelUse = 1/4d,
                Supports = "~B",
                Requirements = "",
                Therms = -5,
            },
            new Card()
            {
                ID = 27,
                OtherSideId = 28,
                Name = "D-D Fusion Magneto-Inertial",
                SpectralType= SpectralType.D,
                Mass = 1,
                RadHard = 3,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 2,
                FuelUse = 1,
                IsSolarPowered = true,
                Supports = "B",
                Requirements = "",
            },
            new Card()
            {
                ID = 28,
                OtherSideId = 27,
                Name = "H-B Fusion Reciprocating Plasmoid",
                SpectralType= SpectralType.D,
                Mass = 0,
                RadHard = 7,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 4,
                FuelUse = 1/2d,
                Supports = "B",
                Requirements = "",
                Therms = -3,
            },
            new Card()
            {
                ID = 29,
                OtherSideId = 30,
                Name = "D-T Fusion Takomak",
                SpectralType= SpectralType.H,
                Mass = 3,
                RadHard = 5,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 3,
                FuelUse = 1/2d,
                Supports = "~",
                Requirements = "",
                Therms = -2,
            },
            new Card()
            {
                ID = 30,
                OtherSideId = 29,
                Name = "Antimatter GDM",
                SpectralType= SpectralType.H,
                Mass = 0,
                RadHard = 9,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 0,
                FuelUse = 1/4d,
                Supports = "X~B",
                Requirements = "",
                Therms = -3,
            },
            new Card()
            {
                ID = 31,
                OtherSideId = 32,
                Name = "D-T Gun Fusion",
                SpectralType= SpectralType.H,
                Mass = 1,
                RadHard = 9,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 1,
                FuelUse = 1/4d,
                Supports = "B",
                Requirements = "c",
            },
            new Card()
            {
                ID = 32,
                OtherSideId = 31,
                Name = "Macron Blowpipe Fusion",
                SpectralType= SpectralType.H,
                Mass = 0,
                RadHard = 10,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 0,
                FuelUse = 1/10d,
                Supports = "X~B",
                Requirements = "c",
            },
            new Card()
            {
                ID = 33,
                OtherSideId = 34,
                Name = "Lyman Alpha Trap",
                SpectralType= SpectralType.S,
                Mass = 2,
                RadHard = 4,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = -2,
                FuelUse = 1,
                Supports = "XB",
                Requirements = "",
            },
            new Card()
            {
                ID = 34,
                OtherSideId = 33,
                Name = "Free Radical Hydrogen Trap",
                SpectralType= SpectralType.S,
                Mass = 0,
                RadHard = 4,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 0,
                FuelUse = 1/2d,
                Supports = "XB",
                Requirements = "",
                Therms = -1,
            },
            new Card()
            {
                ID = 35,
                OtherSideId = 36,
                Name = "Metallic Hydrogen",
                SpectralType= SpectralType.V,
                Mass = 0,
                RadHard = 2,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 4,
                FuelUse = 1,
                Supports = "B",
                Requirements = "",
                Therms = -2,
            },
            new Card()
            {
                ID = 36,
                OtherSideId = 35,
                Name = "Fission-Augmented D-T Inertial Fusion",
                SpectralType= SpectralType.V,
                Mass = 1,
                RadHard = 7,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 7,
                FuelUse = 1,
                Supports = "B",
                Requirements = "",
                Therms = -2,
            },
            new Card()
            {
                ID = 37,
                OtherSideId = 38,
                Name = "Mini-Mag RF Paul Trap",
                SpectralType= SpectralType.C,
                Mass = 1,
                RadHard = 2,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = -3,
                FuelUse = 1,
                Supports = "X",
                Requirements = "",
                Ability = "SCOOP: -2 ISRU for Colocated ISRU platforms at Aerostat Sites.",
                HasPacman = true,
            },
            new Card()
            {
                ID = 38,
                OtherSideId = 37,
                Name = "Ultracold Neutrons",
                SpectralType= SpectralType.C,
                Mass = 1,
                RadHard = 5,
                Type = CardType.Reactor,
                IsThrustModificator = false,
                Supports = "XB",
                Requirements = "",
                Ability = "SCOOP: -2 ISRU for Colocated ISRU platforms at Aerostat Sites."
            },
            new Card()
            {
                ID = 39,
                OtherSideId = 40,
                Name = "Pebble Bed Fission",
                SpectralType= SpectralType.S,
                Mass = 1,
                RadHard = 6,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 4,
                FuelUse = 1,
                Supports = "~",
                Requirements = "",
                Therms = -1,
            },
            new Card()
            {
                ID = 40,
                OtherSideId = 39,
                Name = "VCR Light Bulb Fission",
                SpectralType= SpectralType.S,
                Mass = 0,
                RadHard = 6,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 2,
                FuelUse = 1/2d,
                Supports = "~",
                Requirements = "",
                Therms = -1,
            },
            new Card()
            {
                ID = 41,
                OtherSideId = 42,
                Name = "Penning Trap",
                SpectralType= SpectralType.H,
                Mass = 2,
                RadHard = 3,
                Type = CardType.Reactor,
                IsThrustModificator = false,
                Supports = "XB",
                Requirements = "",
            },
            new Card()
            {
                ID = 42,
                OtherSideId = 41,
                Name = "3He-D Fusion Mirror Cell",
                SpectralType= SpectralType.H,
                Mass = 1,
                RadHard = 5,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 0,
                FuelUse = 1/4d,
                Supports = "~",
                Requirements = "",
                Therms = -1,
            },
            new Card()
            {
                ID = 43,
                OtherSideId = 44,
                Name = "Project Orion",
                SpectralType= SpectralType.S,
                Mass = 6,
                RadHard = 8,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 7,
                FuelUse = 1,
                Supports = "B",
                Requirements = "",
                Therms = -1,
            },
            new Card()
            {
                ID = 44,
                OtherSideId = 43,
                Name = "Project Valkyrie",
                SpectralType= SpectralType.S,
                Mass = 1,
                RadHard = 9,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 8,
                FuelUse = 1/4d,
                Supports = "B",
                Requirements = "X",
                Therms = -3,
                Ability = "When activated, Decommission colocated cards with Rad-Hard <4."
            },
            new Card()
            {
                ID = 45,
                OtherSideId = 46,
                Name = "Rubbie Thin Film Fission Hohlraum",
                SpectralType= SpectralType.M,
                Mass = 1,
                RadHard = 5,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 0,
                FuelUse = 1/2d,
                Supports = "~",
                Requirements = "",
                Therms = -1,
            },
            new Card()
            {
                ID = 46,
                OtherSideId = 45,
                Name = "Positronum Bottle",
                SpectralType= SpectralType.M,
                Mass = 0,
                RadHard = 9,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 0,
                FuelUse = 1/2d,
                Supports = "X~",
                Requirements = "",
                Therms = -1,
            },
            new Card()
            {
                ID = 47,
                OtherSideId = 48,
                Name = "Supercritical Water Fission",
                SpectralType= SpectralType.V,
                Mass = 1,
                RadHard = 7,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 3,
                FuelUse = 1,
                Supports = "~",
                Requirements = "",
                Therms = -2,
            },
            new Card()
            {
                ID = 48,
                OtherSideId = 47,
                Name = "H-6Li Furor",
                SpectralType= SpectralType.V,
                Mass = 0,
                RadHard = 4,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 2,
                FuelUse = 1,
                Supports = "~B",
                Requirements = "",
            },

            #endregion
            #region Rafineries

            new Card()
            {
                ID = 49,
                OtherSideId = 50,
                Name = "Atomic Layer Deposition",
                SpectralType= SpectralType.V,
                Mass = 2,
                RadHard = 2,
                Type = CardType.Rafinery,
                Requirements = "e",
                Ability = "",
            },
            new Card()
            {
                ID = 50,
                OtherSideId = 49,
                Name = "Ilmenite Semiconductor Film",
                SpectralType= SpectralType.V,
                Mass = 2,
                RadHard = 6,
                Type = CardType.Rafinery,
                Requirements = "",
                Ability = "POWER GIRDLE: If used to industrialize a non-atmospheric site of size 8+, you permanently gain the Powersat faction privilege."
            },
            new Card()
            {
                ID = 51,
                OtherSideId = 52,
                Name = "Basalt Fiber Spinning",
                SpectralType= SpectralType.S,
                Mass = 3,
                RadHard = 5,
                Type = CardType.Rafinery,
                Requirements = "x~B",
                Ability = ""
            },
            new Card()
            {
                ID = 52,
                OtherSideId = 51,
                Name = "Von Neumann Santa Claus Machine",
                SpectralType= SpectralType.S,
                Mass = 2,
                RadHard = 5,
                Type = CardType.Rafinery,
                Requirements = "",
                Ability = "DIVINING NUBOTS: -1 ISRU for Colocated ISRU platform."
            },
            new Card()
            {
                ID = 53,
                OtherSideId = 54,
                Name = "CVD Molding",
                SpectralType= SpectralType.M,
                Mass = 3,
                RadHard = 5,
                Type = CardType.Rafinery,
                Requirements = "",
                Ability = ""
            },
            new Card()
            {
                ID = 54,
                OtherSideId = 53,
                Name = "Carbonyl Volatilization",
                SpectralType= SpectralType.M,
                Mass = 2,
                RadHard = 5,
                Type = CardType.Rafinery,
                Requirements = "",
                Ability = "THORIUM BREEDER: -3 to Colocated size rolls on S Sites."
            },
            new Card()
            {
                ID = 55,
                OtherSideId = 56,
                Name = "Carbo-Chlorination",
                SpectralType= SpectralType.V,
                Mass = 2,
                RadHard = 4,
                Type = CardType.Rafinery,
                Requirements = "e",
                Ability = ""
            },
            new Card()
            {
                ID = 56,
                OtherSideId = 55,
                Name = "Solar Carbotherm",
                SpectralType= SpectralType.V,
                Mass = 2,
                RadHard = 5,
                Type = CardType.Rafinery,
                Requirements = "",
                Ability = "ARCOLOGY: Decommissioning of a robonaut is not needed when this is used to industrialize in the zones Mercury, Venus, Earth"
            },
            new Card()
            {
                ID = 57,
                OtherSideId = 58,
                Name = "Electroforming",
                SpectralType= SpectralType.M,
                Mass = 3,
                RadHard = 3,
                Type = CardType.Rafinery,
                Requirements = "e",
                Ability = ""
            },
            new Card()
            {
                ID = 58,
                OtherSideId = 57,
                Name = "Impact Mold Sinter",
                SpectralType= SpectralType.M,
                Mass = 3,
                RadHard = 5,
                Type = CardType.Rafinery,
                Requirements = "",
                Ability = "FOAMED NICKEL: -1 to Colocated size rolls."
            },
            new Card()
            {
                ID = 59,
                OtherSideId = 60,
                Name = "Fluidized Bed",
                SpectralType= SpectralType.V,
                Mass = 3,
                RadHard = 4,
                Type = CardType.Rafinery,
                Requirements = "e",
                Ability = ""
            },
            new Card()
            {
                ID = 60,
                OtherSideId = 59,
                Name = "Atmospheric Scoop",
                SpectralType= SpectralType.V,
                Mass = 1,
                RadHard = 5,
                Type = CardType.Rafinery,
                HasPacman = true,
                Requirements = "e",
                Ability = "SCOOP: If operational, this card makes adjacent or colocated aerostat sites into [2 hydration]"
            },
            new Card()
            {
                ID = 61,
                OtherSideId = 62,
                Name = "Foamglass Sintering",
                SpectralType= SpectralType.D,
                Mass = 3,
                RadHard = 4,
                Type = CardType.Rafinery,
                Requirements = "e",
                Ability = ""
            },
            new Card()
            {
                ID = 62,
                OtherSideId = 61,
                Name = "Laser-Heated Pedestal Growth",
                SpectralType= SpectralType.D,
                Mass = 1,
                RadHard = 5,
                Type = CardType.Rafinery,
                Requirements = "e",
                Ability = "SUPERLENS: -1 to all Colocated raygun size rolls."
            },
            new Card()
            {
                ID = 63,
                OtherSideId = 64,
                Name = "Froth Flotation",
                SpectralType= SpectralType.D,
                Mass = 3,
                RadHard = 5,
                Type = CardType.Rafinery,
                Requirements = "e",
                Ability = ""
            },
            new Card()
            {
                ID = 64,
                OtherSideId = 63,
                Name = "Femtochemistry",
                SpectralType= SpectralType.D,
                Mass = 2,
                RadHard = 8,
                Type = CardType.Rafinery,
                Requirements = "",
                Ability = "SCAVENGING: If Colocated, doubles FTs during site refuel."
            },
            new Card()
            {
                ID = 65,
                OtherSideId = 66,
                Name = "ISRU Sabatier",
                SpectralType= SpectralType.V,
                Mass = 3,
                RadHard = 4,
                Type = CardType.Rafinery,
                Requirements = "e",
                Ability = ""
            },
            new Card()
            {
                ID = 66,
                OtherSideId = 65,
                Name = "Biophytolytic Algal Farm",
                SpectralType= SpectralType.V,
                Mass = 3,
                RadHard = 5,
                Type = CardType.Rafinery,
                Requirements = "",
                Ability = "COMET LICHEN: -2 to Colocated size rolls on D Sites."
            },
            new Card()
            {
                ID = 67,
                OtherSideId = 68,
                Name = "In-Situ Leaching",
                SpectralType= SpectralType.D,
                Mass = 3,
                RadHard = 3,
                Type = CardType.Rafinery,
                Requirements = "X~B",
                Ability = ""
            },
            new Card()
            {
                ID = 68,
                OtherSideId = 67,
                Name = "Termite Nest",
                SpectralType= SpectralType.D,
                Mass = 1,
                RadHard = 3,
                Type = CardType.Rafinery,
                Requirements = "X~B",
                Ability = "MINE REVIVAL: As an op, remove a busted disk and place Claim on a Colocated Site of Size 2+."
            },
            new Card()
            {
                ID = 69,
                OtherSideId = 70,
                Name = "Magma Electrolysis",
                SpectralType= SpectralType.V,
                Mass = 3,
                RadHard = 3,
                Type = CardType.Rafinery,
                Requirements = "e",
                Ability = ""
            },
            new Card()
            {
                ID = 70,
                OtherSideId = 69,
                Name = "Ionosphere Lasing",
                SpectralType= SpectralType.V,
                Mass = 2,
                RadHard = 6,
                Type = CardType.Rafinery,
                Requirements = "",
                Ability = "IONOSAT: If used to industrialize an Atmospheric Site, permanently gain the Powersat faction privilege."
            },
            new Card()
            {
                ID = 71,
                OtherSideId = 72,
                Name = "Supercritical Drying",
                SpectralType= SpectralType.H,
                Mass = 1,
                RadHard = 5,
                Type = CardType.Rafinery,
                Requirements = "X",
                Ability = ""
            },
            new Card()
            {
                ID = 72,
                OtherSideId = 71,
                Name = "Solid Flame",
                SpectralType= SpectralType.H,
                Mass = 0,
                RadHard = 5,
                Type = CardType.Rafinery,
                Requirements = "X",
                Ability = "JELLYBOTS: Colocated industrialization is a free action."
            },

            #endregion
            #region Generators

            new Card()
            {
                ID = 73,
                OtherSideId = 74,
                Name = "AMTEC Thermoelectric",
                SpectralType= SpectralType.C,
                Mass = 1,
                RadHard = 6,
                Type = CardType.Generator,
                IsThrustModificator = false,
                HasPacman = true,
                Supports = "ce",
                Requirements = "~",
                Therms = -1,
            },
            new Card()
            {
                ID = 74,
                OtherSideId = 73,
                Name = "JTEC H2 Thermoelectric",
                SpectralType= SpectralType.C,
                Mass = 1,
                RadHard = 4,
                Type = CardType.Generator,
                IsThrustModificator = true,
                IsSolarPowered = true,
                HasPacman = true,
                Supports = "ce",
                Requirements = "",
            },
            new Card()
            {
                ID = 75,
                OtherSideId = 76,
                Name = "Brayton Turbine",
                SpectralType= SpectralType.C,
                Mass = 1,
                RadHard = 5,
                Type = CardType.Generator,
                IsThrustModificator = false,
                IsSolarPowered = false,
                HasPacman = true,
                Supports = "ce",
                Requirements = "~B",
                Therms = -2,
            },
            new Card()
            {
                ID = 76,
                OtherSideId = 75,
                Name = "O'Meara LSP Paralens",
                SpectralType= SpectralType.C,
                Mass = 0,
                RadHard = 10,
                Type = CardType.Generator,
                IsThrustModificator = true,
                Thrust = 0,
                FuelUse = 1/2d,
                IsSolarPowered = true,
                HasPacman = true,
                Supports = "e",
                Requirements = "",
            },
            new Card()
            {
                ID = 77,
                OtherSideId = 78,
                Name = "Cascade Photovoltaic",
                SpectralType= SpectralType.C,
                Mass = 3,
                RadHard = 1,
                Type = CardType.Generator,
                IsThrustModificator = true,
                IsSolarPowered = true,
                HasPacman = false,
                Supports = "e",
                Requirements = "",
            },
            new Card()
            {
                ID = 78,
                OtherSideId = 77,
                Name = "Buckyball C60 Photovoltaic",
                SpectralType= SpectralType.C,
                Mass = 2,
                RadHard = 3,
                Type = CardType.Generator,
                IsThrustModificator = true,
                Thrust = 1,
                FuelUse = 1,
                IsSolarPowered = true,
                HasPacman = false,
                Supports = "e",
                Requirements = "",
            },
            new Card()
            {
                ID = 79,
                OtherSideId = 80,
                Name = "Cascade Thermoacoustic",
                SpectralType= SpectralType.V,
                Mass = 0,
                RadHard = 5,
                Type = CardType.Generator,
                IsThrustModificator = false,
                HasPacman = false,
                Supports = "e",
                Requirements = "~",
                Therms = -2,
            },
            new Card()
            {
                ID = 80,
                OtherSideId = 79,
                Name = "Dusty Plasma MHD",
                SpectralType= SpectralType.V,
                Mass = 1,
                RadHard = 6,
                Type = CardType.Generator,
                IsThrustModificator = false,
                HasPacman = true,
                Supports = "e",
                Requirements = "",
            },
            new Card()
            {
                ID = 81,
                OtherSideId = 82,
                Name = "Catalyzed Fission Scintillator",
                SpectralType= SpectralType.D,
                Mass = 0,
                RadHard = 7,
                Type = CardType.Generator,
                IsThrustModificator = false,
                HasPacman = false,
                Supports = "ce",
                Requirements = "X",
                Therms = -1,
            },
            new Card()
            {
                ID = 82,
                OtherSideId = 81,
                Name = "Diamonoid Electro-Dynamic Tether",
                SpectralType= SpectralType.D,
                Mass = 2,
                RadHard = 4,
                Type = CardType.Generator,
                IsThrustModificator = false,
                HasPacman = false,
                Supports = "ce",
                Requirements = "",
            },
            new Card()
            {
                ID = 83,
                OtherSideId = 84,
                Name = "Ericsson Engine",
                SpectralType= SpectralType.C,
                Mass = 1,
                RadHard = 5,
                Type = CardType.Generator,
                IsThrustModificator = false,
                HasPacman = true,
                Supports = "e",
                Requirements = "~B",
                Therms = -1,
            },
            new Card()
            {
                ID = 84,
                OtherSideId = 83,
                Name = "Nanocomposite Thermoelectric",
                SpectralType= SpectralType.C,
                Mass = 1,
                RadHard = 5,
                Type = CardType.Generator,
                IsThrustModificator = true,
                Thrust = 1,
                FuelUse = 1,
                HasPacman = true,
                Supports = "e",
                Requirements = "X~B",
            },
            new Card()
            {
                ID = 85,
                OtherSideId = 86,
                Name = "Flywheel Compulsator",
                SpectralType= SpectralType.M,
                Mass = 4,
                RadHard = 4,
                Type = CardType.Generator,
                IsThrustModificator = true,
                IsSolarPowered = true,
                HasPacman = false,
                Supports = "ce",
                Requirements = "",
            },
            new Card()
            {
                ID = 86,
                OtherSideId = 85,
                Name = "Superconducting Adductor",
                SpectralType= SpectralType.M,
                Mass = 1,
                RadHard = 4,
                Type = CardType.Generator,
                IsThrustModificator = false,
                HasPacman = false,
                Supports = "ce",
                Requirements = "",
            },
            new Card()
            {
                ID = 87,
                OtherSideId = 88,
                Name = "H2-O2 Fuel Cell",
                SpectralType= SpectralType.C,
                Mass = 4,
                RadHard = 4,
                Type = CardType.Generator,
                IsThrustModificator = true,
                IsSolarPowered = true,
                HasPacman = false,
                Supports = "e",
                Requirements = "",
            },
            new Card()
            {
                ID = 88,
                OtherSideId = 87,
                Name = "Microbial Fuel Cell",
                SpectralType= SpectralType.C,
                Mass = 2,
                RadHard = 5,
                Type = CardType.Generator,
                IsThrustModificator = true,
                Thrust = 1,
                FuelUse = 1,
                IsSolarPowered = true,
                HasPacman = false,
                Supports = "ce",
                Requirements = "",
            },
            new Card()
            {
                ID = 89,
                OtherSideId = 90,
                Name = "In-Core Thermionic",
                SpectralType= SpectralType.S,
                Mass = 0,
                RadHard = 6,
                Type = CardType.Generator,
                IsThrustModificator = false,
                HasPacman = true,
                Supports = "ce",
                Requirements = "~B",
                Therms = -2,
            },
            new Card()
            {
                ID = 90,
                OtherSideId = 89,
                Name = "Z-Pinch Microfission",
                SpectralType= SpectralType.S,
                Mass = 2,
                RadHard = 9,
                Type = CardType.Generator,
                IsThrustModificator = true,
                Thrust = 4,
                FuelUse = 1,
                HasPacman = true,
                Supports = "ce",
                Requirements = "",
                Therms = -1,
            },
            new Card()
            {
                ID = 91,
                OtherSideId = 92,
                Name = "Magnetoshell Plasma Parachute",
                SpectralType= SpectralType.S,
                Mass = 0,
                RadHard = 5,
                Type = CardType.Generator,
                IsThrustModificator = true,
                Thrust = -2,
                FuelUse = 1,
                IsSolarPowered = true,
                HasPacman = false,
                Supports = "e",
                Requirements = "",
                Ability = "This stack can safely enter aerobrakes. Cannot be used to support Bernals or during industrialization."
            },
            new Card()
            {
                ID = 92,
                OtherSideId = 91,
                Name = "Granular Rainbow Corral",
                SpectralType= SpectralType.S,
                Mass = 0,
                RadHard = 10,
                Type = CardType.Generator,
                IsThrustModificator = true,
                IsSolarPowered = true,
                HasPacman = false,
                Supports = "e",
                Requirements = "",
                Ability = "This stack can safely enter aerobrakes."
            },
            new Card()
            {
                ID = 93,
                OtherSideId = 94,
                Name = "Marx Capacitor Bank",
                SpectralType= SpectralType.M,
                Mass = 1,
                RadHard = 4,
                Type = CardType.Generator,
                IsThrustModificator = false,
                HasPacman = false,
                Supports = "c",
                Requirements = "e",
            },
            new Card()
            {
                ID = 94,
                OtherSideId = 93,
                Name = "Casimir Battery",
                SpectralType= SpectralType.M,
                Mass = 0,
                RadHard = 3,
                Type = CardType.Generator,
                IsThrustModificator = false,
                HasPacman = false,
                Supports = "c",
                Requirements = "e",
            },
            new Card()
            {
                ID = 95,
                OtherSideId = 96,
                Name = "Optoelectric Nuclear Battery",
                SpectralType= SpectralType.V,
                Mass = 2,
                RadHard = 6,
                Type = CardType.Generator,
                IsThrustModificator = false,
                HasPacman = true,
                Supports = "e",
                Requirements = "",
                Therms = -2,
            },
            new Card()
            {
                ID = 96,
                OtherSideId = 95,
                Name = "Nuclear-Pumped Excimer Flashlamp",
                SpectralType= SpectralType.V,
                Mass = 0,
                RadHard = 8,
                Type = CardType.Generator,
                IsThrustModificator = true,
                Thrust = 1,
                FuelUse = 1,
                HasPacman = true,
                Supports = "e",
                Requirements = "~B",
                Therms = -3,
            },
            new Card()
            {
                ID = 97,
                OtherSideId = 98,
                Name = "Photon Tether Rectenna",
                SpectralType= SpectralType.V,
                Mass = 2,
                RadHard = 2,
                Type = CardType.Generator,
                IsThrustModificator = true,
                Thrust = -1,
                FuelUse = 1,
                IsSolarPowered = true,
                HasPacman = false,
                Supports = "e",
                Requirements = "",
            },
            new Card()
            {
                ID = 98,
                OtherSideId = 97,
                Name = "Palmer LSP Aerosol Lens",
                SpectralType= SpectralType.V,
                Mass = 0,
                RadHard = 10,
                Type = CardType.Generator,
                IsThrustModificator = true,
                Thrust = 1,
                FuelUse = 1,
                IsSolarPowered = true,
                HasPacman = true,
                Supports = "e",
                Requirements = "",
            },
            new Card()
            {
                ID = 99,
                OtherSideId = 100,
                Name = "Radioisotope Stirling",
                SpectralType= SpectralType.M,
                Mass = 3,
                RadHard = 4,
                Type = CardType.Generator,
                IsThrustModificator = true,
                Thrust = -2,
                FuelUse = 1,
                IsSolarPowered = false,
                HasPacman = false,
                Supports = "e",
                Requirements = "",
            },
            new Card()
            {
                ID = 100,
                OtherSideId = 99,
                Name = "Triggered Decay Nuclear Battery",
                SpectralType= SpectralType.M,
                Mass = 1,
                RadHard = 6,
                Type = CardType.Generator,
                IsThrustModificator = false,
                HasPacman = false,
                Supports = "ce",
                Requirements = "",
            },
            new Card()
            {
                ID = 101,
                OtherSideId = 102,
                Name = "Rankine MHD",
                SpectralType= SpectralType.M,
                Mass = 0,
                RadHard = 4,
                Type = CardType.Generator,
                IsThrustModificator = false,
                HasPacman = true,
                Supports = "e",
                Requirements = "~B",
                Therms = -2,
            },
            new Card()
            {
                ID = 102,
                OtherSideId = 101,
                Name = "MHD Open-Cycle",
                SpectralType= SpectralType.M,
                Mass = 0,
                RadHard = 4,
                Type = CardType.Generator,
                IsThrustModificator = true,
                Thrust = 1,
                FuelUse = 1,
                HasPacman = true,
                Supports = "ce",
                Requirements = "B",
            },
            new Card()
            {
                ID = 103,
                OtherSideId = 104,
                Name = "Rankine Solar Dynamic",
                SpectralType= SpectralType.D,
                Mass = 2,
                RadHard = 4,
                Type = CardType.Generator,
                IsThrustModificator = true,
                IsSolarPowered = true,
                HasPacman = false,
                Supports = "e",
                Requirements = "",
                Therms = -1,
            },
            new Card()
            {
                ID = 104,
                OtherSideId = 103,
                Name = "Rankine Multiphase",
                SpectralType= SpectralType.D,
                Mass = 0,
                RadHard = 4,
                Type = CardType.Generator,
                IsThrustModificator = false,
                HasPacman = false,
                Supports = "ce",
                Requirements = "X~B",
            },
            new Card()
            {
                ID = 105,
                OtherSideId = 106,
                Name = "Solar Stirling",
                SpectralType= SpectralType.C,
                Mass = 3,
                RadHard = 5,
                Type = CardType.Generator,
                IsThrustModificator = true,
                IsSolarPowered = true,
                HasPacman = false,
                Supports = "e",
                Requirements = "",
                Therms = -1,
            },
            new Card()
            {
                ID = 106,
                OtherSideId = 105,
                Name = "Thermo-Photovoltaic",
                SpectralType= SpectralType.C,
                Mass = 2,
                RadHard = 4,
                Type = CardType.Generator,
                IsThrustModificator = true,
                Thrust = 1,
                FuelUse = 1,
                IsSolarPowered = true,
                HasPacman = false,
                Supports = "e",
                Requirements = "",
            },

            #endregion
            #region Radiatiors
            
            new Card()
            {
                ID = 107,
                OtherSideId = 108,
                RadiatorOtherWeightId = 109,
                Name = "Bubble Membrane (Light)",
                SpectralType= SpectralType.C,
                Mass = 0,
                RadHard = 1,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 1,
            },
            new Card()
            {
                ID = 108,
                OtherSideId = 107,
                RadiatorOtherWeightId = 110,
                Name = "Electrostatic Membrane (Light)",
                SpectralType= SpectralType.C,
                Mass = 0,
                RadHard = 3,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 1,
            },
            new Card()
            {
                ID = 109,
                OtherSideId = 110,
                RadiatorOtherWeightId = 107,
                Name = "Bubble Membrane (Heavy)",
                SpectralType= SpectralType.C,
                Mass = 1,
                RadHard = 0,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 2,
            },
            new Card()
            {
                ID = 110,
                OtherSideId = 109,
                RadiatorOtherWeightId = 108,
                Name = "Electrostatic Membrane (Heavy)",
                SpectralType= SpectralType.C,
                Mass = 1,
                RadHard = 2,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 3,
            },
            new Card()
            {
                ID = 111,
                OtherSideId = 112,
                RadiatorOtherWeightId = 113,
                Name = "Dielectric X-Ray Window (Light)",
                SpectralType= SpectralType.D,
                Mass = 4,
                RadHard = 7,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 2,
            },
            new Card()
            {
                ID = 112,
                OtherSideId = 111,
                RadiatorOtherWeightId = 114,
                Name = "Graphene Crystal X-Ray Mirror (Light)",
                SpectralType= SpectralType.D,
                Mass = 0,
                RadHard = 7,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 1,
            },
            new Card()
            {
                ID = 113,
                OtherSideId = 114,
                RadiatorOtherWeightId = 111,
                Name = "Dielectric X-Ray Window (Heavy)",
                SpectralType= SpectralType.D,
                Mass = 5,
                RadHard = 7,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 3,
            },
            new Card()
            {
                ID = 114,
                OtherSideId = 113,
                RadiatorOtherWeightId = 112,
                Name = "Graphene Crystal X-Ray Mirror (Heavy)",
                SpectralType= SpectralType.D,
                Mass = 1,
                RadHard = 7,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 2,
            },
            new Card()
            {
                ID = 115,
                OtherSideId = 116,
                RadiatorOtherWeightId = 117,
                Name = "ETHER Charged Dust (Light)",
                SpectralType= SpectralType.M,
                Mass = 1,
                RadHard = 1,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 1,
            },
            new Card()
            {
                ID = 116,
                OtherSideId = 115,
                RadiatorOtherWeightId = 119,
                Name = "Curie Point (Light)",
                SpectralType= SpectralType.M,
                Mass = 0,
                RadHard = 5,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 1,
            },
            new Card()
            {
                ID = 118,
                OtherSideId = 119,
                RadiatorOtherWeightId = 115,
                Name = "ETHER Charged Dust (Heavy)",
                SpectralType= SpectralType.M,
                Mass = 2,
                RadHard = 1,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 2,
            },
            new Card()
            {
                ID = 119,
                OtherSideId = 118,
                RadiatorOtherWeightId = 117,
                Name = "Curie Point (Heavy)",
                SpectralType= SpectralType.M,
                Mass = 1,
                RadHard = 3,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 3,
            },
            new Card()
            {
                ID = 120,
                OtherSideId = 121,
                RadiatorOtherWeightId = 122,
                Name = "Li Heatsink Fountain (Light)",
                SpectralType= SpectralType.S,
                Mass = 2,
                RadHard = 6,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 1,
            },
            new Card()
            {
                ID = 121,
                OtherSideId = 120,
                RadiatorOtherWeightId = 123,
                Name = "Thermochemical Heatsink Fountain (Light)",
                SpectralType= SpectralType.S,
                Mass = 1,
                RadHard = 6,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 1,
            },
            new Card()
            {
                ID = 122,
                OtherSideId = 123,
                RadiatorOtherWeightId = 120,
                Name = "Li Heatsink Fountain (Heavy)",
                SpectralType= SpectralType.S,
                Mass = 3,
                RadHard = 6,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 5,
                Ability = "Switch to light side after 1st use."
            },
            new Card()
            {
                ID = 123,
                OtherSideId = 122,
                RadiatorOtherWeightId = 121,
                Name = "Thermochemical Heatsink Fountain (Heavy)",
                SpectralType= SpectralType.S,
                Mass = 2,
                RadHard = 6,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 6,
                Ability = "Switch to light side after 1st use."
            },
            new Card()
            {
                ID = 124,
                OtherSideId = 125,
                RadiatorOtherWeightId = 126,
                Name = "Magnetocaloric Refrigerator (Light)",
                SpectralType= SpectralType.S,
                Mass = 2,
                RadHard = 6,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "e",
                Therms = 3,
            },
            new Card()
            {
                ID = 125,
                OtherSideId = 124,
                RadiatorOtherWeightId = 127,
                Name = "Nuclear Fuel Spin Polarizer (Light)",
                SpectralType= SpectralType.S,
                Mass = 0,
                RadHard = 5,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 1,
            },
            new Card()
            {
                ID = 126,
                OtherSideId = 127,
                RadiatorOtherWeightId = 124,
                Name = "Magnetocaloric Refrigerator (Heavy)",
                SpectralType= SpectralType.S,
                Mass = 3,
                RadHard = 6,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "e",
                Therms = 4,
            },
            new Card()
            {
                ID = 127,
                OtherSideId = 126,
                RadiatorOtherWeightId = 125,
                Name = "Nuclear Fuel Spin Polarizer (Heavy)",
                SpectralType= SpectralType.S,
                Mass = 1,
                RadHard = 4,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 2,
            },
            new Card()
            {
                ID = 128,
                OtherSideId = 129,
                RadiatorOtherWeightId = 130,
                Name = "Microtube Array (Light)",
                SpectralType= SpectralType.C,
                Mass = 2,
                RadHard = 1,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 2,
            },
            new Card()
            {
                ID = 129,
                OtherSideId = 128,
                RadiatorOtherWeightId = 131,
                Name = "Marangoni Flow (Light)",
                SpectralType= SpectralType.C,
                Mass = 0,
                RadHard = 2,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 2,
            },
            new Card()
            {
                ID = 130,
                OtherSideId = 131,
                RadiatorOtherWeightId = 128,
                Name = "Microtube Array (Heavy)",
                SpectralType= SpectralType.C,
                Mass = 3,
                RadHard = 0,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 3,
            },
            new Card()
            {
                ID = 131,
                OtherSideId = 130,
                RadiatorOtherWeightId = 129,
                Name = "Marangoni Flow (Heavy)",
                SpectralType= SpectralType.C,
                Mass = 1,
                RadHard = 1,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 3,
            },
            new Card()
            {
                ID = 132,
                OtherSideId = 133,
                RadiatorOtherWeightId = 134,
                Name = "Mo / Li Heat Pipe (Light)",
                SpectralType= SpectralType.M,
                Mass = 1,
                RadHard = 2,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 2,
            },
            new Card()
            {
                ID = 133,
                OtherSideId = 132,
                RadiatorOtherWeightId = 135,
                Name = "Tin Droplet (Light)",
                SpectralType= SpectralType.M,
                Mass = 0,
                RadHard = 3,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 2,
            },
            new Card()
            {
                ID = 134,
                OtherSideId = 135,
                RadiatorOtherWeightId = 132,
                Name = "Mo / Li Heat Pipe (Heavy)",
                SpectralType= SpectralType.M,
                Mass = 2,
                RadHard = 1,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 2,
            },
            new Card()
            {
                ID = 135,
                OtherSideId = 134,
                RadiatorOtherWeightId = 133,
                Name = "Tin Droplet (Heavy)",
                SpectralType= SpectralType.M,
                Mass = 1,
                RadHard = 2,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 2,
            },
            new Card()
            {
                ID = 136,
                OtherSideId = 137,
                RadiatorOtherWeightId = 138,
                Name = "Qu Tube (Light)",
                SpectralType= SpectralType.M,
                Mass = 1,
                RadHard = 4,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 1,
            },
            new Card()
            {
                ID = 137,
                OtherSideId = 136,
                RadiatorOtherWeightId = 139,
                Name = "ANDR / In Dream Pipe (Light)",
                SpectralType= SpectralType.M,
                Mass = 0,
                RadHard = 3,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 2,
            },
            new Card()
            {
                ID = 138,
                OtherSideId = 139,
                RadiatorOtherWeightId = 136,
                Name = "Qu Tube (Heavy)",
                SpectralType= SpectralType.M,
                Mass = 4,
                RadHard = 2,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 2,
            },
            new Card()
            {
                ID = 139,
                OtherSideId = 138,
                RadiatorOtherWeightId = 137,
                Name = "ANDR / In Dream Pipe (Heavy)",
                SpectralType= SpectralType.M,
                Mass = 1,
                RadHard = 2,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 3,
            },
            new Card()
            {
                ID = 140,
                OtherSideId = 141,
                RadiatorOtherWeightId = 142,
                Name = "SS / NaK Pumped Loop (Light)",
                SpectralType= SpectralType.M,
                Mass = 2,
                RadHard = 1,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 2,
            },
            new Card()
            {
                ID = 141,
                OtherSideId = 140,
                RadiatorOtherWeightId = 143,
                Name = "Hula-Hoop (Light)",
                SpectralType= SpectralType.M,
                Mass = 1,
                RadHard = 6,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 2,
            },
            new Card()
            {
                ID = 142,
                OtherSideId = 143,
                RadiatorOtherWeightId = 140,
                Name = "SS / NaK Pumped Loop (Heavy)",
                SpectralType= SpectralType.M,
                Mass = 4,
                RadHard = 0,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 3,
            },
            new Card()
            {
                ID = 143,
                OtherSideId = 142,
                RadiatorOtherWeightId = 141,
                Name = "Hula-Hoop (Heavy)",
                SpectralType= SpectralType.M,
                Mass = 2,
                RadHard = 6,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 3,
            },
            new Card()
            {
                ID = 144,
                OtherSideId = 145,
                RadiatorOtherWeightId = 146,
                Name = "Salt-Cooled Reflux Tube (Light)",
                SpectralType= SpectralType.C,
                Mass = 3,
                RadHard = 4,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 2,
            },
            new Card()
            {
                ID = 145,
                OtherSideId = 144,
                RadiatorOtherWeightId = 146,
                Name = "Buckytube Filament (Light)",
                SpectralType= SpectralType.C,
                Mass = 0,
                RadHard = 4,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 2,
            },
            new Card()
            {
                ID = 146,
                OtherSideId = 147,
                RadiatorOtherWeightId = 144,
                Name = "Salt-Cooled Reflux Tube (Heavy)",
                SpectralType= SpectralType.C,
                Mass = 4,
                RadHard = 4,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 3,
            },
            new Card()
            {
                ID = 147,
                OtherSideId = 146,
                RadiatorOtherWeightId = 145,
                Name = "Buckytube Filament (Heavy)",
                SpectralType= SpectralType.C,
                Mass = 1,
                RadHard = 3,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 3,
            },
            new Card()
            {
                ID = 148,
                OtherSideId = 149,
                RadiatorOtherWeightId = 150,
                Name = "Steel / Pb-Bi Pumped Loop (Light)",
                SpectralType= SpectralType.M,
                Mass = 2,
                RadHard = 3,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 1,
            },
            new Card()
            {
                ID = 149,
                OtherSideId = 148,
                RadiatorOtherWeightId = 151,
                Name = "Pulsating Heat Pipe (Light)",
                SpectralType= SpectralType.M,
                Mass = 1,
                RadHard = 1,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 2,
            },
            new Card()
            {
                ID = 150,
                OtherSideId = 151,
                RadiatorOtherWeightId = 148,
                Name = "Steel / Pb-Bi Pumped Loop (Heavy)",
                SpectralType= SpectralType.M,
                Mass = 4,
                RadHard = 2,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 2,
            },
            new Card()
            {
                ID = 151,
                OtherSideId = 150,
                RadiatorOtherWeightId = 149,
                Name = "Pulsating Heat Pipe (Heavy)",
                SpectralType= SpectralType.M,
                Mass = 2,
                RadHard = 1,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 4,
            },
            new Card()
            {
                ID = 152,
                OtherSideId = 153,
                RadiatorOtherWeightId = 154,
                Name = "Ti / K Heat Pipe (Light)",
                SpectralType= SpectralType.M,
                Mass = 2,
                RadHard = 3,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 1,
            },
            new Card()
            {
                ID = 153,
                OtherSideId = 152,
                RadiatorOtherWeightId = 155,
                Name = "Flux-Pinned Superthermal (Light)",
                SpectralType= SpectralType.M,
                Mass = 1,
                RadHard = 5,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 1,
            },
            new Card()
            {
                ID = 154,
                OtherSideId = 155,
                RadiatorOtherWeightId = 152,
                Name = "Ti / K Heat Pipe (Heavy)",
                SpectralType= SpectralType.M,
                Mass = 4,
                RadHard = 2,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 2,
            },
            new Card()
            {
                ID = 155,
                OtherSideId = 154,
                RadiatorOtherWeightId = 153,
                Name = "Flux-Pinned Superthermal (Heavy)",
                SpectralType= SpectralType.M,
                Mass = 2,
                RadHard = 5,
                Type = CardType.Radiator,
                Supports = "",
                Requirements = "",
                Therms = 3,
            },

            #endregion
            #region Robonauts

            new Card()
            {
                ID = 156,
                OtherSideId = 157,
                Name = "Blackbody-Pumped Laser",
                SpectralType= SpectralType.S,
                Mass = 0,
                RadHard = 5,
                Type = CardType.Robonaut,
                RobonautType = RobonautType.Laser,
                ISRU = 2,
                Requirements = "~B",
                Therms = -1,
            },
            new Card()
            {
                ID = 157,
                OtherSideId = 156,
                Name = "Fissile Aerosol Laser",
                SpectralType= SpectralType.S,
                Mass = 0,
                RadHard = 7,
                Type = CardType.Robonaut,
                RobonautType = RobonautType.Laser,
                ISRU = 2,
                Requirements = "",
                Therms = -1,
            },
            new Card()
            {
                ID = 158,
                OtherSideId = 159,
                Name = "Cat Fusion Z-pinch Torch",
                SpectralType= SpectralType.D,
                Mass = 0,
                RadHard = 2,
                Type = CardType.Robonaut,
                RobonautType = RobonautType.Rover,
                ISRU = 2,
                Requirements = "X",
                Therms = -1,
            },
            new Card()
            {
                ID = 159,
                OtherSideId = 158,
                Name = "H-B Cat Inertial",
                SpectralType= SpectralType.D,
                Thrust = 4,
                FuelUse = 1/3d,
                AfterBurn = 1,
                Mass = 2,
                RadHard = 2,
                Type = CardType.Robonaut,
                RobonautType = RobonautType.Missile,
                ISRU = 0,
                Requirements = "X",
                Therms = -1,
            },
            new Card()
            {
                ID = 160,
                OtherSideId = 161,
                Name = "Flywheel Tractor",
                SpectralType= SpectralType.D,
                Mass = 0,
                RadHard = 5,
                Type = CardType.Robonaut,
                RobonautType = RobonautType.Rover,
                ISRU = 3,
                Requirements = "e",
            },
            new Card()
            {
                ID = 161,
                OtherSideId = 160,
                Name = "Electrophoretic Sandworm",
                SpectralType= SpectralType.D,
                Mass = 1,
                RadHard = 5,
                Type = CardType.Robonaut,
                RobonautType = RobonautType.Rover,
                ISRU = 1,
                Requirements = "",
            },
            new Card()
            {
                ID = 162,
                OtherSideId = 163,
                Name = "Free Electron Laser",
                SpectralType= SpectralType.S,
                Mass = 2,
                RadHard = 4,
                Type = CardType.Robonaut,
                RobonautType = RobonautType.Laser,
                ISRU = 1,
                Requirements = "c",
                Therms = -1,
            },
            new Card()
            {
                ID = 163,
                OtherSideId = 162,
                Name = "Wakefield e-Beam",
                SpectralType= SpectralType.S,
                Thrust = 4,
                FuelUse = 2,
                AfterBurn = 2,
                Mass = 0,
                RadHard = 5,
                Type = CardType.Robonaut,
                RobonautType = RobonautType.Missile,
                ISRU = 1,
                Requirements = "c",
            },
            new Card()
            {
                ID = 164,
                OtherSideId = 165,
                Name = "Kuck Mosquito",
                SpectralType= SpectralType.D,
                Thrust = 10,
                FuelUse = 8,
                AfterBurn = 2,
                Mass = 0,
                RadHard = 6,
                Type = CardType.Robonaut,
                RobonautType = RobonautType.Missile,
                ISRU = 3,
                Requirements = "B",
            },
            new Card()
            {
                ID = 165,
                OtherSideId = 164,
                Name = "Ablative Laser",
                SpectralType= SpectralType.D,
                Thrust = 3,
                FuelUse = 1,
                AfterBurn = 3,
                IsPushable = true,
                IsSolarPowered = true,
                Mass = 0,
                RadHard = 6,
                Type = CardType.Robonaut,
                RobonautType = RobonautType.Missile,
                ISRU = 2,
                Requirements = "",
            },
            new Card()
            {
                ID = 166,
                OtherSideId = 167,
                Name = "MET Steamer",
                SpectralType= SpectralType.C,
                Thrust = 5,
                FuelUse = 4,
                AfterBurn = 1,
                IsPushable = true,
                Mass = 1,
                RadHard = 4,
                Type = CardType.Robonaut,
                RobonautType = RobonautType.Missile,
                ISRU = 2,
                Requirements = "e",
            },
            new Card()
            {
                ID = 167,
                OtherSideId = 166,
                Name = "Nanobot",
                SpectralType= SpectralType.C,
                Mass = 0,
                RadHard = 5,
                Type = CardType.Robonaut,
                RobonautType = RobonautType.Rover,
                ISRU = 1,
                Requirements = "",
            },
            new Card()
            {
                ID = 168,
                OtherSideId = 169,
                Name = "Neutral Beam",
                SpectralType= SpectralType.S,
                Mass = 2,
                RadHard = 5,
                Type = CardType.Robonaut,
                RobonautType = RobonautType.Laser,
                ISRU = 2,
                Requirements = "c",
            },
            new Card()
            {
                ID = 169,
                OtherSideId = 168,
                Name = "D-D Fusion Inertial",
                SpectralType= SpectralType.S,
                Thrust = 3,
                FuelUse = 1/2d,
                AfterBurn = 1,
                Mass = 1,
                RadHard = 4,
                Type = CardType.Robonaut,
                RobonautType = RobonautType.Missile,
                ISRU = 1,
                Requirements = "c",
                Therms = -2,
            },
            new Card()
            {
                ID = 170,
                OtherSideId = 171,
                Name = "Nuclear Drill",
                SpectralType= SpectralType.D,
                Thrust = 5,
                FuelUse = 4,
                AfterBurn = 1,
                IsPushable = true,
                Mass = 1,
                RadHard = 6,
                Type = CardType.Robonaut,
                RobonautType = RobonautType.Missile,
                ISRU = 3,
                Requirements = "~",
            },
            new Card()
            {
                ID = 171,
                OtherSideId = 170,
                Name = "Helical Railgun",
                SpectralType= SpectralType.D,
                Thrust = 5,
                FuelUse = 4,
                IsPushable = true,
                Mass = 2,
                RadHard = 8,
                Type = CardType.Robonaut,
                RobonautType = RobonautType.Missile,
                ISRU = 0,
                Requirements = "c",
                Ability = "Missile + Laser"
            },
            new Card()
            {
                ID = 172,
                OtherSideId = 173,
                Name = "Phase-Locked Diode Laser",
                SpectralType= SpectralType.C,
                Mass = 1,
                RadHard = 3,
                Type = CardType.Robonaut,
                RobonautType = RobonautType.Laser,
                ISRU = 3,
                Requirements = "e",
            },
            new Card()
            {
                ID = 173,
                OtherSideId = 172,
                Name = "Lorentz-Propelled Microprobe",
                SpectralType= SpectralType.C,
                Mass = 0,
                RadHard = 3,
                Type = CardType.Robonaut,
                RobonautType = RobonautType.Laser,
                ISRU = 3,
                Requirements = "",
                Ability = "NANITES: One re-roll if fail 1 or more size rolls."
            },
            new Card()
            {
                ID = 174,
                OtherSideId = 175,
                Name = "Rock Splitter",
                SpectralType= SpectralType.V,
                Mass = 0,
                RadHard = 5,
                Type = CardType.Robonaut,
                RobonautType = RobonautType.Rover,
                ISRU = 4,
                Requirements = "e",
            },
            new Card()
            {
                ID = 175,
                OtherSideId = 174,
                Name = "MagBeam",
                SpectralType= SpectralType.V,
                Thrust = 4,
                FuelUse = 1,
                AfterBurn = 1,
                IsPushable = true,
                IsSolarPowered = true,
                Mass = 1,
                RadHard = 5,
                Type = CardType.Robonaut,
                RobonautType = RobonautType.Missile,
                ISRU = 3,
                Requirements = "",
                Ability = "Missile + Laser, -1 ISRU, +3 thrust if pushed by Powersat."
            },
            new Card()
            {
                ID = 176,
                OtherSideId = 177,
                Name = "Solar-Pumped MHD Exciplex Laser",
                SpectralType= SpectralType.C,
                Mass = 3,
                RadHard = 4,
                Type = CardType.Robonaut,
                RobonautType = RobonautType.Laser,
                ISRU = 2,
                Requirements = "",
                Therms = -2,
            },
            new Card()
            {
                ID = 177,
                OtherSideId = 176,
                Name = "Quantum Cascade Laser",
                SpectralType= SpectralType.C,
                Mass = 1,
                RadHard = 5,
                Type = CardType.Robonaut,
                RobonautType = RobonautType.Laser,
                ISRU = 0,
                Requirements = "e",
                Therms = -1,
            },
            new Card()
            {
                ID = 178,
                OtherSideId = 179,
                Name = "Tungsten Resistojet",
                SpectralType= SpectralType.M,
                Thrust = 5,
                FuelUse = 4,
                AfterBurn = 1,
                IsPushable = true,
                Mass = 0,
                RadHard = 5,
                Type = CardType.Robonaut,
                RobonautType = RobonautType.Missile,
                ISRU = 3,
                Requirements = "e",
            },
            new Card()
            {
                ID = 179,
                OtherSideId = 178,
                Name = "MITEE Arcjet",
                SpectralType= SpectralType.M,
                Thrust = 4,
                FuelUse = 2,
                AfterBurn = 2,
                IsPushable = true,
                Mass = 0,
                RadHard = 4,
                Type = CardType.Robonaut,
                RobonautType = RobonautType.Missile,
                ISRU = 1,
                Requirements = "e",
            },
            

            #endregion

        };
    }
}