using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Threading.Tasks;
using HFCA;
using SQLite;

namespace HFCA
{
    public class CardDatabase
    {
        readonly SQLiteAsyncConnection _database;

        public CardDatabase(string dbPath)
        {
            _database = new SQLiteAsyncConnection(dbPath);
#if DEBUG
            _database.DropTableAsync<Card>().Wait();
#endif
            var result = _database.CreateTableAsync<Card>().Result;
            if (result == CreateTableResult.Created)
                _database.InsertAllAsync(Data);
        }

        public ObservableCollection<Card> GetCards()
        {
            return new ObservableCollection<Card>(_database.Table<Card>().ToListAsync().Result);
        }

        public Task<Card> GetCard(int id)
        {
            return _database.GetAsync<Card>(id);
        }

        private List<Card> Data => new List<Card>()
        {
            #region Thrusters
            new Card()
            {
                ID = 1,
                OtherSideId = 2,
                SpectralType = SpectralType.V,
                Name = "Ablative Plate\r\n",
                Type = CardType.Thruster,
                Mass = 1,
                RadHard = 7,
                Thrust = 2,
                FuelUse = 2,
                FreeTurns = 0,
                AfterBurn = 1,
                IsPushable = true,
                IsSolarPowered = false,
                Requirements = "XB",
            },
            new Card()
            {
                ID = 2,
                OtherSideId = 1,
                Name = "Ablative Nozzle",
                SpectralType= SpectralType.V,
                Mass = 0,
                RadHard = 8,
                Type = CardType.Thruster,
                Thrust= 3,
                FuelUse = 2,
                FreeTurns = 0,
                AfterBurn = 1,
                IsPushable = true,
                IsSolarPowered = false,
                Requirements = "X~B",
            },
            new Card()
            {
                ID = 3,
                OtherSideId = 4,
                Name = "De Laval Nozzle",
                SpectralType= SpectralType.M,
                Mass = 0,
                RadHard = 6,
                Type = CardType.Thruster,
                Thrust= 5,
                FuelUse = 4,
                FreeTurns = 0,
                AfterBurn = 2,
                IsPushable = false,
                IsSolarPowered = false,
                Requirements = "~B",
            },
            new Card()
            {
                ID = 4,
                OtherSideId = 3,
                Name = "Magnetic Nozzle",
                SpectralType= SpectralType.M,
                Mass = 0,
                RadHard = 5,
                Type = CardType.Thruster,
                Thrust= 3,
                FuelUse = 1,
                FreeTurns = 0,
                AfterBurn = 3,
                IsPushable = false,
                IsSolarPowered = false,
                Requirements = "~",
            },
            new Card()
            {
                ID = 5,
                OtherSideId = 6,
                Name = "Dumbo",
                SpectralType= SpectralType.S,
                Mass = 0,
                RadHard = 7,
                Type = CardType.Thruster,
                Thrust= 6,
                FuelUse = 5,
                FreeTurns = 0,
                AfterBurn = 1,
                IsPushable = false,
                IsSolarPowered = false,
                Requirements = "~B",
            },
            new Card()
            {
                ID = 6,
                OtherSideId = 5,
                Name = "Timberwind",
                SpectralType= SpectralType.S,
                Mass = 0,
                RadHard = 7,
                Type = CardType.Thruster,
                Thrust= 5,
                FuelUse = 3,
                FreeTurns = 0,
                AfterBurn = 1,
                IsPushable = false,
                IsSolarPowered = false,
                Requirements = "X~B",
            },
            new Card()
            {
                ID = 7,
                OtherSideId = 8,
                Name = "Hall Effect",
                SpectralType= SpectralType.C,
                Mass = 2,
                RadHard = 5,
                Type = CardType.Thruster,
                Thrust= 3,
                FuelUse = 2,
                FreeTurns = 0,
                AfterBurn = 0,
                IsPushable = true,
                IsSolarPowered = false,
                Requirements = "e",
            },
            new Card()
            {
                ID = 8,
                OtherSideId = 7,
                Name = "Ion Drive",
                SpectralType= SpectralType.C,
                Mass = 1,
                RadHard = 5,
                Type = CardType.Thruster,
                Thrust= 2,
                FuelUse = 0.5d,
                FreeTurns = 1,
                AfterBurn = 1,
                IsPushable = true,
                IsSolarPowered = false,
                Requirements = "e",
            },
            new Card()
            {
                ID = 9,
                OtherSideId = 10,
                Name = "Mass Driver",
                SpectralType= SpectralType.M,
                Mass = 3,
                RadHard = 8,
                Type = CardType.Thruster,
                Thrust= 4,
                FuelUse = 3,
                FreeTurns = 0,
                AfterBurn = 0,
                IsPushable = true,
                IsSolarPowered = false,
                Requirements = "c",
            },
            new Card()
            {
                ID = 10,
                OtherSideId = 9,
                Name = "MPD T-wave",
                SpectralType= SpectralType.M,
                Mass = 1,
                RadHard = 9,
                Type = CardType.Thruster,
                Thrust= 2,
                FuelUse = 0.5d,
                FreeTurns = 0,
                AfterBurn = 0,
                IsPushable = true,
                IsSolarPowered = false,
                Requirements = "c",
            },
            new Card()
            {
                ID = 11,
                OtherSideId = 12,
                Name = "Metastable Helium",
                SpectralType= SpectralType.V,
                Mass = 1,
                RadHard = 0,
                Type = CardType.Thruster,
                Thrust= 5,
                FuelUse = 1,
                FreeTurns = 0,
                AfterBurn = 1,
                IsPushable = false,
                IsSolarPowered = false,
                Requirements = "Xt",
            },
            new Card()
            {
                ID = 12,
                OtherSideId = 11,
                Name = "n-6Li Microfission",
                SpectralType= SpectralType.V,
                Mass = 1,
                RadHard = 8,
                Type = CardType.Thruster,
                Thrust= 5,
                FuelUse = 0.5d,
                FreeTurns = 0,
                AfterBurn = 1,
                IsPushable = false,
                IsSolarPowered = false,
                Requirements = "Xt",
            },
            new Card()
            {
                ID = 13,
                OtherSideId = 14,
                Name = "Monoatomic Plug Nozzle",
                SpectralType= SpectralType.M,
                Mass = 0,
                RadHard = 6,
                Type = CardType.Thruster,
                Thrust= 4,
                FuelUse = 3,
                FreeTurns = 0,
                AfterBurn = 1,
                IsPushable = false,
                IsSolarPowered = false,
                Requirements = "~",
            },
            new Card()
            {
                ID = 14,
                OtherSideId = 13,
                Name = "Vortex Confined Nozzle",
                SpectralType= SpectralType.M,
                Mass = 0,
                RadHard = 7,
                Type = CardType.Thruster,
                Thrust= 4,
                FuelUse = 2,
                FreeTurns = 0,
                AfterBurn = 1,
                IsPushable = false,
                IsSolarPowered = false,
                Requirements = "~t",
            },
            new Card()
            {
                ID = 15,
                OtherSideId = 16,
                Name = "Photon Heliogyro",
                SpectralType= SpectralType.C,
                Mass = 0,
                RadHard = 1,
                Type = CardType.Thruster,
                Thrust= 0,
                FuelUse = 0,
                FreeTurns = 1,
                AfterBurn = 0,
                IsPushable = true,
                IsSolarPowered = true,
                Requirements = "",
                Ability = "Aerobrake decommission. Immune to Flare & Belt Rolls.",
            },
            new Card()
            {
                ID = 16,
                OtherSideId = 15,
                Name = "Electric Sail",
                SpectralType= SpectralType.C,
                Mass = 0,
                RadHard = 2,
                Type = CardType.Thruster,
                Thrust= 2,
                FuelUse = 0,
                FreeTurns = 1,
                AfterBurn = 0,
                IsPushable = true,
                IsSolarPowered = true,
                Requirements = "",
                Ability = "Aerobrake decommission. Immune to Flare & Belt Rolls.",
            },
            new Card()
            {
                ID = 17,
                OtherSideId = 18,
                Name = "Photon Kite Sail",
                SpectralType= SpectralType.C,
                Mass = 0,
                RadHard = 0,
                Type = CardType.Thruster,
                Thrust= 0,
                FuelUse = 0,
                FreeTurns = 1,
                AfterBurn = 0,
                IsPushable = true,
                IsSolarPowered = true,
                Requirements = "",
                Ability = "Aerobrake decommission. Immune to Flare & Belt Rolls.",
            },
            new Card()
            {
                ID = 18,
                OtherSideId = 17,
                Name = "Mag Sail",
                SpectralType= SpectralType.C,
                Mass = 0,
                RadHard = 4,
                Type = CardType.Thruster,
                Thrust= 1,
                FuelUse = 0,
                FreeTurns = 1,
                AfterBurn = 0,
                IsPushable = true,
                IsSolarPowered = true,
                Requirements = "",
                Ability = "Aerobrake decommission. Each Radiation Belt entered = Bonus Burn",
            },
            new Card()
            {
                ID = 19,
                OtherSideId = 20,
                Name = "Ponderomotive VASIMR",
                SpectralType= SpectralType.V,
                Mass = 1,
                RadHard = 4,
                Type = CardType.Thruster,
                Thrust= 3,
                FuelUse = 1,
                FreeTurns = 0,
                AfterBurn = 1,
                IsPushable = true,
                IsSolarPowered = false,
                Requirements = "c",
            },
            new Card()
            {
                ID = 20,
                OtherSideId = 19,
                Name = "Pulsed Plasmoid",
                SpectralType= SpectralType.V,
                Mass = 1,
                RadHard = 5,
                Type = CardType.Thruster,
                Thrust = 3,
                FuelUse = 1,
                FreeTurns = 0,
                AfterBurn = 0,
                IsPushable = true,
                IsSolarPowered = true,
                Requirements = "",
            },
            new Card()
            {
                ID = 21,
                OtherSideId = 22,
                Name = "Pulsed Inductive",
                SpectralType= SpectralType.C,
                Mass = 1,
                RadHard = 5,
                Type = CardType.Thruster,
                Thrust = 4,
                FuelUse = 2,
                FreeTurns = 0,
                AfterBurn = 0,
                IsPushable = true,
                IsSolarPowered = false,
                Requirements = "c",
            },
            new Card()
            {
                ID = 22,
                OtherSideId = 21,
                Name = "Dual-Stage 4-Grid",
                SpectralType= SpectralType.C,
                Mass = 0,
                RadHard = 5,
                Type = CardType.Thruster,
                Thrust = 2,
                FuelUse = 1/3d,
                FreeTurns = 1,
                AfterBurn = 0,
                IsPushable = true,
                IsSolarPowered = false,
                Requirements = "e",
            },
            new Card()
            {
                ID = 23,
                OtherSideId = 24,
                Name = "Re Solar Moth",
                SpectralType= SpectralType.D,
                Mass = 0,
                RadHard = 5,
                Type = CardType.Thruster,
                Thrust = 3,
                FuelUse = 4,
                FreeTurns = 0,
                AfterBurn = 2,
                IsPushable = true,
                IsSolarPowered = true,
                Requirements = "",
            },
            new Card()
            {
                ID = 24,
                OtherSideId = 23,
                Name = "Colliding Beam H-B Fusion",
                SpectralType= SpectralType.D,
                Mass = 2,
                RadHard = 5,
                Type = CardType.Thruster,
                Thrust = 3,
                FuelUse = 0.1d,
                FreeTurns = 1,
                AfterBurn = 2,
                IsPushable = false,
                IsSolarPowered = false,
                Requirements = "et",
            },
            #endregion
            #region Reactors
            new Card()
            {
                ID = 25,
                OtherSideId = 26,
                Name = "Cermet NERVA Fission",
                SpectralType= SpectralType.S,
                Mass = 1,
                RadHard = 7,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 3,
                FuelUse = 1,
                Supports = "~",
                Requirements = "",
            },
            new Card()
            {
                ID = 26,
                OtherSideId = 25,
                Name = "Pulsed NTR Fission",
                SpectralType= SpectralType.S,
                Mass = 0,
                RadHard = 7,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 0,
                FuelUse = 1/4d,
                Supports = "~B",
                Requirements = "ttttt",
            },
            new Card()
            {
                ID = 27,
                OtherSideId = 28,
                Name = "D-D Fusion Magneto-Inertial",
                SpectralType= SpectralType.D,
                Mass = 1,
                RadHard = 3,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 2,
                FuelUse = 1,
                IsSolarPowered = true,
                Supports = "B",
                Requirements = "",
            },
            new Card()
            {
                ID = 28,
                OtherSideId = 27,
                Name = "H-B Fusion Reciprocating Plasmoid",
                SpectralType= SpectralType.D,
                Mass = 0,
                RadHard = 7,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 4,
                FuelUse = 1/2d,
                Supports = "B",
                Requirements = "ttt",
            },
            new Card()
            {
                ID = 29,
                OtherSideId = 30,
                Name = "D-T Fusion Takomak",
                SpectralType= SpectralType.H,
                Mass = 3,
                RadHard = 5,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 3,
                FuelUse = 1/2d,
                Supports = "~",
                Requirements = "tt",
            },
            new Card()
            {
                ID = 30,
                OtherSideId = 29,
                Name = "Antimatter GDM",
                SpectralType= SpectralType.H,
                Mass = 0,
                RadHard = 9,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 0,
                FuelUse = 1/4d,
                Supports = "X~B",
                Requirements = "ttt",
            },
            new Card()
            {
                ID = 31,
                OtherSideId = 32,
                Name = "D-T Gun Fusion",
                SpectralType= SpectralType.H,
                Mass = 1,
                RadHard = 9,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 1,
                FuelUse = 1/4d,
                Supports = "B",
                Requirements = "c",
            },
            new Card()
            {
                ID = 32,
                OtherSideId = 31,
                Name = "Macron Blowpipe Fusion",
                SpectralType= SpectralType.H,
                Mass = 0,
                RadHard = 10,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 0,
                FuelUse = 1/10d,
                Supports = "X~B",
                Requirements = "c",
            },
            new Card()
            {
                ID = 33,
                OtherSideId = 34,
                Name = "Lyman Alpha Trap",
                SpectralType= SpectralType.S,
                Mass = 2,
                RadHard = 4,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = -2,
                FuelUse = 1,
                Supports = "XB",
                Requirements = "",
            },
            new Card()
            {
                ID = 34,
                OtherSideId = 33,
                Name = "Free Radical Hydrogen Trap",
                SpectralType= SpectralType.S,
                Mass = 0,
                RadHard = 4,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 0,
                FuelUse = 1/2d,
                Supports = "XB",
                Requirements = "t",
            },
            new Card()
            {
                ID = 35,
                OtherSideId = 36,
                Name = "Metallic Hydrogen",
                SpectralType= SpectralType.V,
                Mass = 0,
                RadHard = 2,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 4,
                FuelUse = 1,
                Supports = "B",
                Requirements = "tt",
            },
            new Card()
            {
                ID = 36,
                OtherSideId = 35,
                Name = "Fission-Augmented D-T Inertial Fusion",
                SpectralType= SpectralType.V,
                Mass = 1,
                RadHard = 7,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 7,
                FuelUse = 1,
                Supports = "B",
                Requirements = "tt",
            },
            new Card()
            {
                ID = 37,
                OtherSideId = 38,
                Name = "Mini-Mag RF Paul Trap",
                SpectralType= SpectralType.C,
                Mass = 1,
                RadHard = 2,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = -3,
                FuelUse = 1,
                Supports = "X",
                Requirements = "",
                Ability = "SCOOP: -2 ISRU for Colocated ISRU platforms at Aerostat Sites.",
                HasPacman = true,
            },
            new Card()
            {
                ID = 38,
                OtherSideId = 37,
                Name = "Ultracold Neutrons",
                SpectralType= SpectralType.C,
                Mass = 1,
                RadHard = 5,
                Type = CardType.Reactor,
                IsThrustModificator = false,
                Supports = "XB",
                Requirements = "",
                Ability = "SCOOP: -2 ISRU for Colocated ISRU platforms at Aerostat Sites."
            },
            new Card()
            {
                ID = 39,
                OtherSideId = 40,
                Name = "Pebble Bed Fission",
                SpectralType= SpectralType.S,
                Mass = 1,
                RadHard = 6,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 4,
                FuelUse = 1,
                Supports = "~",
                Requirements = "t",
            },
            new Card()
            {
                ID = 40,
                OtherSideId = 39,
                Name = "VCR Light Bulb Fission",
                SpectralType= SpectralType.S,
                Mass = 0,
                RadHard = 6,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 2,
                FuelUse = 1/2d,
                Supports = "~",
                Requirements = "t",
            },
            new Card()
            {
                ID = 41,
                OtherSideId = 42,
                Name = "Penning Trap",
                SpectralType= SpectralType.H,
                Mass = 2,
                RadHard = 3,
                Type = CardType.Reactor,
                IsThrustModificator = false,
                Supports = "XB",
                Requirements = "",
            },
            new Card()
            {
                ID = 42,
                OtherSideId = 41,
                Name = "3He-D Fusion Mirror Cell",
                SpectralType= SpectralType.H,
                Mass = 1,
                RadHard = 5,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 0,
                FuelUse = 1/4d,
                Supports = "~",
                Requirements = "t",
            },
            new Card()
            {
                ID = 43,
                OtherSideId = 44,
                Name = "Project Orion",
                SpectralType= SpectralType.S,
                Mass = 6,
                RadHard = 8,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 7,
                FuelUse = 1,
                Supports = "B",
                Requirements = "t",
            },
            new Card()
            {
                ID = 44,
                OtherSideId = 43,
                Name = "Project Valkyrie",
                SpectralType= SpectralType.S,
                Mass = 1,
                RadHard = 9,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 8,
                FuelUse = 1/4d,
                Supports = "B",
                Requirements = "Xttt",
                Ability = "When activated, Decommission colocated cards with Rad-Hard <4."
            },
            new Card()
            {
                ID = 45,
                OtherSideId = 46,
                Name = "Rubbie Thin Film Fission Hohlraum",
                SpectralType= SpectralType.M,
                Mass = 1,
                RadHard = 5,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 0,
                FuelUse = 1/2d,
                Supports = "~",
                Requirements = "t",
            },
            new Card()
            {
                ID = 46,
                OtherSideId = 45,
                Name = "Positronum Bottle",
                SpectralType= SpectralType.M,
                Mass = 0,
                RadHard = 9,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 0,
                FuelUse = 1/2d,
                Supports = "X~",
                Requirements = "t",
            },
            new Card()
            {
                ID = 47,
                OtherSideId = 48,
                Name = "Supercritical Water Fission",
                SpectralType= SpectralType.V,
                Mass = 1,
                RadHard = 7,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 3,
                FuelUse = 1,
                Supports = "~",
                Requirements = "tt",
            },
            new Card()
            {
                ID = 48,
                OtherSideId = 47,
                Name = "H-6Li Furor",
                SpectralType= SpectralType.V,
                Mass = 0,
                RadHard = 4,
                Type = CardType.Reactor,
                IsThrustModificator = true,
                Thrust = 2,
                FuelUse = 1,
                Supports = "~B",
                Requirements = "",
            },

            #endregion
        };
    }
}